name: Publish Library

# 워크플로가 실행될 조건을 정의합니다.
on:
  # 1. 새 GitHub Release가 생성될 때 실행
  release:
    types: [created]
    
  # 3. GitHub UI에서 수동으로 워크플로를 실행할 수 있도록 허용
  workflow_dispatch:

# 워크플로 내에서 실행될 작업(jobs)들을 정의합니다.
jobs:
  publish: # 작업 이름 (원하는 대로 지정)
    runs-on: ubuntu-latest # 이 작업이 실행될 가상 머신 환경 (최신 Ubuntu LTS 버전)

    # 권한 부여
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Publish to MavenCentral
        run: ./gradlew publish --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
